/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gzlkemhmupdpvghxrujg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6bGtlbWhtdXBkcHZnaHhydWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0OTA5OTAsImV4cCI6MjA4NDA2Njk5MH0.NsFg2mqPTUYpEEl4Jhpfambhu-H-Q0ycei-CMNpdeW8"